/************************************************************
 * Generated by SoftTree SQL Assistant © 7.5.502
 * Time:   25.02.2018 16:14:57
 * Source: APPPTPR
 ************************************************************/
 SET IDENTITY_INSERT Dispancer.dbo.appptpr on
 
/* Inserting [Dispensary13102017].[dbo].[APPPTPR] data... */
INSERT INTO [Dispancer].[dbo].[APPPTPR]([APPPTPR],[Name])
VALUES(1,'ÕÂÚ  ');
INSERT INTO [Dispancer].[dbo].[APPPTPR]([APPPTPR],[Name])
VALUES(2,'¿œœœ ');
INSERT INTO [Dispancer].[dbo].[APPPTPR]([APPPTPR],[Name])
VALUES(3,'“œ–  ');
SET IDENTITY_INSERT Dispancer.dbo.appptpr OFF
/* Inserted 3 rows */

/* Successfully inserted 3 rows in 1 table. */
