/************************************************************
 * Generated by SoftTree SQL Assistant © 7.5.502
 * Time:   25.02.2018 16:35:50
 * Source: BenefitsCategory
 ************************************************************/

/* Inserting [Dispancer].[dbo].[BenefitsCategory] data... */
 SET IDENTITY_INSERT Dispancer.dbo.benefitscategory on
INSERT INTO [Dispancer].[dbo].[BenefitsCategory]([BenefitsCategoryID],[Name],[NotaBene])
VALUES(1,'Дети войны',NULL);
INSERT INTO [Dispancer].[dbo].[BenefitsCategory]([BenefitsCategoryID],[Name],[NotaBene])
VALUES(2,'Пенсионеры',NULL);
INSERT INTO [Dispancer].[dbo].[BenefitsCategory]([BenefitsCategoryID],[Name],[NotaBene])
VALUES(3,'ЧАЭС',NULL);
INSERT INTO [Dispancer].[dbo].[BenefitsCategory]([BenefitsCategoryID],[Name],[NotaBene])
VALUES(4,'Инвалиды ВОВ',NULL);
INSERT INTO [Dispancer].[dbo].[BenefitsCategory]([BenefitsCategoryID],[Name],[NotaBene])
VALUES(5,'УБД',NULL);
INSERT INTO [Dispancer].[dbo].[BenefitsCategory]([BenefitsCategoryID],[Name],[NotaBene])
VALUES(6,'Инвалиды СА',NULL);
INSERT INTO [Dispancer].[dbo].[BenefitsCategory]([BenefitsCategoryID],[Name],[NotaBene])
VALUES(7,'УВОВ',NULL);
INSERT INTO [Dispancer].[dbo].[BenefitsCategory]([BenefitsCategoryID],[Name],[NotaBene])
VALUES(8,'Другие ивалиды',NULL);
 SET IDENTITY_INSERT Dispancer.dbo.benefitscategory off
/* Inserted 8 rows */

/* Successfully inserted 8 rows in 1 table. */
