/************************************************************
 * Generated by SoftTree SQL Assistant © 7.5.502
 * Time:   25.02.2018 16:27:42
 * Source: AdminDivision
 ************************************************************/

/* Inserting [Dispancer][dbo].[AdminDivision] data... */
SET IDENTITY_INSERT Dispancer.dbo.admindivision on
INSERT INTO [Dispancer].[dbo].[AdminDivision]([AdminDivisionID],[Level],[Name],[SocrName],[CodeType])
VALUES(1,1,'Область                      ','обл       ',101);
INSERT INTO [Dispancer].[dbo].[AdminDivision]([AdminDivisionID],[Level],[Name],[SocrName],[CodeType])
VALUES(2,1,'Автономная республика        ','АР        ',102);
INSERT INTO [Dispancer].[dbo].[AdminDivision]([AdminDivisionID],[Level],[Name],[SocrName],[CodeType])
VALUES(3,2,'Район                        ','р-н       ',201);
INSERT INTO [Dispancer].[dbo].[AdminDivision]([AdminDivisionID],[Level],[Name],[SocrName],[CodeType])
VALUES(4,3,'Посёлок городского типа      ','пгт       ',302);
INSERT INTO [Dispancer].[dbo].[AdminDivision]([AdminDivisionID],[Level],[Name],[SocrName],[CodeType])
VALUES(5,3,'Город                        ','г         ',301);
INSERT INTO [Dispancer].[dbo].[AdminDivision]([AdminDivisionID],[Level],[Name],[SocrName],[CodeType])
VALUES(6,3,'Село                         ','с         ',303);
INSERT INTO [Dispancer].[dbo].[AdminDivision]([AdminDivisionID],[Level],[Name],[SocrName],[CodeType])
VALUES(7,3,'Посёлок                      ','п         ',304);
 SET IDENTITY_INSERT Dispancer.dbo.admindivision off
/* Inserted 7 rows */

/* Successfully inserted 7 rows in 1 table. */
