/************************************************************
 * Generated by SoftTree SQL Assistant © 7.5.502
 * Time:   25.02.2018 16:34:40
 * Source: ChiperRecept
 ************************************************************/

/* Inserting [Dispancer].[dbo].[ChiperRecept] data... */
 SET IDENTITY_INSERT Dispancer.dbo.chiperrecept on
INSERT INTO [Dispancer].[dbo].[ChiperRecept]([ChiperReceptID],[Name],[NotaBene])
VALUES(1,'01',NULL);
INSERT INTO [Dispancer].[dbo].[ChiperRecept]([ChiperReceptID],[Name],[NotaBene])
VALUES(2,'',NULL);
INSERT INTO [Dispancer].[dbo].[ChiperRecept]([ChiperReceptID],[Name],[NotaBene])
VALUES(3,'48',NULL);
INSERT INTO [Dispancer].[dbo].[ChiperRecept]([ChiperReceptID],[Name],[NotaBene])
VALUES(4,'27',NULL);
INSERT INTO [Dispancer].[dbo].[ChiperRecept]([ChiperReceptID],[Name],[NotaBene])
VALUES(5,'28',NULL);
INSERT INTO [Dispancer].[dbo].[ChiperRecept]([ChiperReceptID],[Name],[NotaBene])
VALUES(6,'02',NULL);
INSERT INTO [Dispancer].[dbo].[ChiperRecept]([ChiperReceptID],[Name],[NotaBene])
VALUES(7,'0',NULL);
 SET IDENTITY_INSERT Dispancer.dbo.chiperrecept off
/* Inserted 7 rows */

/* Successfully inserted 7 rows in 1 table. */
