/************************************************************
 * Generated by SoftTree SQL Assistant © 7.5.502
 * Time:   25.02.2018 16:30:37
 * Source: TypeStreet
 ************************************************************/

/* Inserting [Dispancer].[dbo].[TypeStreet] data... */
 SET IDENTITY_INSERT Dispancer.dbo.typestreet on
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Аал                          ','аал       ',532,2);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Абонентский ящик             ','а/я       ',572,3);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Аллея                        ','аллея     ',501,4);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Арбан                        ','арбан     ',560,5);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Аул                          ','аул       ',533,6);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Балка                        ','балка     ',581,7);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Берег                        ','берег     ',573,8);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Бугор                        ','бугор     ',576,9);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Бульвар                      ','б-р       ',502,10);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Бухта                        ','бухта     ',582,11);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Вал                          ','вал       ',568,12);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Въезд                        ','въезд     ',503,13);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Выселки(ок)                  ','высел     ',534,14);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Гаражно-строит-ный кооператив','гск       ',563,15);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Горка                        ','горка     ',586,16);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Городок                      ','городок   ',535,17);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Дачное нек                   ','днп       ',587,18);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Деревня                      ','д         ',536,19);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Дорога                       ','дор       ',504,20);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'ж/д останов. (обгонный) пункт','ж/д_оп    ',539,21);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Железнодорожная будка        ','ж/д_будка ',537,22);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Железнодорожная казарма      ','ж/д_казарм',538,23);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Железнодорожная платформа    ','ж/д_платф ',559,24);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Железнодорожная станция      ','ж/д_ст    ',542,25);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Железнодорожный пост         ','ж/д_пост  ',540,26);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Железнодорожный разъезд      ','ж/д_рзд   ',541,27);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Животноводческая точка       ','жт        ',505,28);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Заезд                        ','заезд     ',506,29);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Зона                         ','зона      ',577,30);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Казарма                      ','казарма   ',543,31);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Канал                        ','канал     ',562,32);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Квартал                      ','кв-л      ',507,33);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Километр                     ','км        ',508,34);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Кольцо                       ','кольцо    ',509,35);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Коса                         ','коса      ',567,36);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Леспромхоз                   ','лпх       ',565,37);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Линия                        ','линия     ',510,38);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Маяк                         ','маяк      ',585,39);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Местечко                     ','м         ',544,40);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Местность                    ','местность ',580,41);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Микрорайон                   ','мкр       ',545,42);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Мост                         ','мост      ',570,43);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Мыс                          ','мыс       ',584,44);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Набережная                   ','наб       ',511,45);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Населенный пункт             ','нп        ',546,46);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Некоммерче                   ','н/п       ',588,47);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Остров                       ','остров    ',512,48);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Парк                         ','парк      ',513,49);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Переезд                      ','переезд   ',515,50);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Переулок                     ','пер       ',514,51);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Планировочный район          ','п/р       ',550,52);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Платформа                    ','платф     ',547,53);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Площадка                     ','пл-ка     ',517,54);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Площадь                      ','пл        ',516,55);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Полустанок                   ','полустанок',552,56);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Поселок                      ','п         ',548,57);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Поселок и(при) станция(и)    ','п/ст      ',551,58);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Починок                      ','починок   ',553,59);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Почтовое отделение           ','п/о       ',549,60);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Причал                       ','причал    ',583,61);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Проезд                       ','проезд    ',518,62);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Просек                       ','просек    ',520,63);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Просека                      ','просека   ',574,64);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Проселок                     ','проселок  ',521,65);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Проспект                     ','пр-кт     ',519,66);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Проток                       ','проток    ',566,67);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Протока                      ','протока   ',575,68);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Проулок                      ','проулок   ',522,69);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Разъезд                      ','рзд       ',554,70);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Ряды                         ','ряды      ',571,71);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Сад                          ','сад       ',523,72);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Садов-е неком-е товарищество ','снт       ',564,73);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Село                         ','с         ',555,74);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Сквер                        ','сквер     ',524,75);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Слобода                      ','сл        ',556,76);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Спуск                        ','спуск     ',561,77);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Станция                      ','ст        ',557,78);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Строение                     ','стр       ',525,79);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Территория                   ','тер       ',526,80);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'тоннель                      ','тоннель   ',579,81);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Тракт                        ','тракт     ',527,82);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Тупик                        ','туп       ',528,83);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Улица                        ','ул        ',529,84);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Участок                      ','уч-к      ',530,85);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Ферма                        ','ферма     ',569,86);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Фермерское                   ','ф/х       ',589,87);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Хутор                        ','х         ',558,88);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Шоссе                        ','ш         ',531,89);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'эстакада                     ','эстакада  ',578,90);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Двор                         ','двор      ',590,91);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Санаторий','Санаторий',591,93);
INSERT INTO [Dispancer].[dbo].[TypeStreet]([Level],[Name],[SocrName],[CodeType],[TypeStreetID])
VALUES(5,'Монастырь','монастырь',592,95);
 SET IDENTITY_INSERT Dispancer.dbo.typestreet off
/* Inserted 92 rows */

/* Successfully inserted 92 rows in 1 table. */
