/************************************************************
 * Generated by SoftTree SQL Assistant © 7.5.502
 * Time:   25.02.2018 16:38:25
 * Source: WhyDeRegister
 ************************************************************/

/* Inserting [Dispancer].[dbo].[WhyDeRegister] data... */
 SET IDENTITY_INSERT Dispancer.dbo.whyderegister on
INSERT INTO [Dispancer].[dbo].[WhyDeRegister]([WhyDeRegisterID],[Name],[NotaBene])
VALUES(1,'выздоровление\стойко','В архив не входит?');
INSERT INTO [Dispancer].[dbo].[WhyDeRegister]([WhyDeRegisterID],[Name],[NotaBene])
VALUES(2,'перемена места жител','В архи');
INSERT INTO [Dispancer].[dbo].[WhyDeRegister]([WhyDeRegisterID],[Name],[NotaBene])
VALUES(3,'Смерть','В архив');
INSERT INTO [Dispancer].[dbo].[WhyDeRegister]([WhyDeRegisterID],[Name],[NotaBene])
VALUES(4,'Другие причины','В архив не в ходит');
INSERT INTO [Dispancer].[dbo].[WhyDeRegister]([WhyDeRegisterID],[Name],[NotaBene])
VALUES(5,'по достижению возрас','В архив не въодит');
INSERT INTO [Dispancer].[dbo].[WhyDeRegister]([WhyDeRegisterID],[Name],[NotaBene])
VALUES(6,'Переведен на другой ','В архив не входит');
INSERT INTO [Dispancer].[dbo].[WhyDeRegister]([WhyDeRegisterID],[Name],[NotaBene])
VALUES(7,'Переведен в ДПХ',NULL);
INSERT INTO [Dispancer].[dbo].[WhyDeRegister]([WhyDeRegisterID],[Name],[NotaBene])
VALUES(8,'[пусто]','ничего');
 SET IDENTITY_INSERT Dispancer.dbo.whyderegister OFF
/* Inserted 8 rows */

/* Successfully inserted 8 rows in 1 table. */
